# Generated by Django 2.1 on 2018-11-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_account_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Meeting'), (2, 'Phone'), (3, 'Email')])),
                ('date', models.DateField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'verbose_name_plural': 'communications',
            },
        ),
    ]
