# Generated by Django 2.1 on 2018-11-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20181113_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='owner',
        ),
    ]
